version: 2
updates:
  - package-ecosystem: pip
    directory: '/'
    schedule:
      interval: weekly
      day: sunday
      time: '12:00'
      timezone: 'Asia/Tokyo'
    reviewers:
      - disVill
  - package-ecosystem: npm
    directory: '/client'
    schedule:
      interval: weekly
      day: sunday
      time: '12:00'
      timezone: 'Asia/Tokyo'
    reviewers:
      - takumah
