# Generated by Django 4.1.1 on 2022-09-24 16:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import quizzes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, unique=True, verbose_name='Quiz number')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Quiz Title')),
                ('statement', models.TextField(blank=True, null=True, verbose_name='Quiz Statement')),
                ('flag', models.CharField(max_length=100, unique=True, validators=[quizzes.models.FlagValidator()], verbose_name='Flag')),
                ('difficulty', models.PositiveIntegerField(verbose_name='Difficulty')),
                ('point', models.PositiveIntegerField(verbose_name='Point')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='Author')),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
                ('created_at', models.DateTimeField(editable=False, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated at')),
                ('is_extra', models.BooleanField(default=False, verbose_name='Is extra')),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.CreateModel(
            name='QuizAppendedUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='QuizCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Quiz categories',
            },
        ),
        migrations.CreateModel(
            name='QuizFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('file', models.FileField(upload_to='quiz_files/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Solved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved_at', models.DateTimeField(editable=False, verbose_name='Solved date')),
            ],
            options={
                'verbose_name': 'Solved user',
                'verbose_name_plural': 'Solved users',
            },
        ),
        migrations.CreateModel(
            name='SubmitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(max_length=100, verbose_name='Flag')),
                ('created_at', models.DateTimeField(editable=False, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(verbose_name='Updated at')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz')),
                ('solved', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.solved')),
            ],
        ),
    ]
