# Generated by Django 4.1.1 on 2022-09-24 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solved',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz'),
        ),
        migrations.AddField(
            model_name='solved',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz', to='quizzes.quizcategory'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='file',
            field=models.ManyToManyField(blank=True, related_name='quiz', to='quizzes.quizfile'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='solved_users',
            field=models.ManyToManyField(related_name='solved_quizzes', through='quizzes.Solved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='url',
            field=models.ManyToManyField(blank=True, related_name='quiz', to='quizzes.quizappendedurl'),
        ),
    ]
