# Generated by Django 4.1.6 on 2023-02-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_configurations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="value",
            field=models.CharField(default="0", max_length=1000),
        ),
    ]
