# Generated by Django 4.1.1 on 2022-10-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='fixed',
            field=models.BooleanField(default=False, help_text='Trueにするとgame_configurationの設定に関わらずスコアが変動しなくなります', verbose_name='Fixed'),
        ),
    ]
