# Generated by Django 4.1.5 on 2023-02-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0003_quiz_fixed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="is_extra",
            field=models.BooleanField(default=False, help_text="Trueにするとextra問題として扱われます", verbose_name="Is extra"),
        ),
    ]
